#!/bin/sh /etc/rc.common

START=99
STOP=10

LOG_FILE="/tmp/autoip-all.log"

start() {
    echo "Starting monitor-ping..."
    chmod +x /usr/bin/mahavpn-ping.sh
    chmod +x /usr/bin/mahavpn-modem.py
    chmod +x /usr/bin/lockband.py
    /usr/bin/mahavpn-ping.sh >> $LOG_FILE 2>&1 &
}

stop() {
    echo "Stopping monitor-ping..."
    kill $(pgrep -f /usr/bin/mahavpn-ping.sh) >/dev/null 2>&1
    kill $(pgrep -f /usr/bin/mahavpn-modem.py) >/dev/null 2>&1
}

restart() {
    stop
    sleep 1
    start
}

enable() {
    echo "Enabling autoip service..."
    [ -e /etc/rc.d/S99autoip ] || ln -s /etc/init.d/autoip /etc/rc.d/S99autoip >/dev/null 2>&1
    stop
    sleep 1
    start
}

disable() {
    echo "Disabling autoip service..."
    rm -f /etc/rc.d/S99autoip /tmp/autoip-all.log /tmp/autoip-offline.log /tmp/autoip-sendbot.txt /tmp/autoip-sendbot.log >/dev/null 2>&1
    stop
}
