#!/bin/bash
#mahavpn
#goodboy
owner=$(curl https://raw.githubusercontent.com/GboyGud/clash_for_android/main/assets/owner)
clear
echo -e ""
echo -e ""
echo -e "            #%%+ :##########################+-.   "                             
echo -e "             ..    .....:######################=   "                            
echo -e "  -======.  .============+##*=-::::-=*###########=   "                           
echo -e "   =++++++:  .=====+*######=.  :::     .+##########    "                          
echo -e "  ..    ............=####*.  .+++++--:   :*########*+-:  "                        
echo -e " *%%* -##################:  .:++++++++-.  :########====**+-  "                    
echo -e "                 :#######   ++++++-=++++-  ########=++=-:-=++-  "                 
echo -e "   =+++- -=======*#######   .:::-==:::::   ########++++++=+=-=*-  "              
echo -e "   =+++- -==========*####=     :###%=     +########--:::---=+++##:  "             
echo -e "                    =#####=    -%#*%*   .+#########    .::-=+*#%#-    "           
echo -e "       *%%+  -##############=:  .--:  :=##########*:-+*****#%%%%%#=:   "          
echo -e "        ..                .####*++++*#############*==---:::...:-+*#*+   "         
echo -e "      ===========- .======+#####################=.                 :+=   "        
echo -e ""
echo -e "              _____              __ ___            "
echo -e "             / ___/___  ___  ___/ // _ ) ___  __ __"
echo -e "            / (_ // _ \/ _ \/ _  // _  |/ _ \/ // /"
echo -e "            \___/ \___/\___/\_,_//____/ \___/\_, / "
echo -e "                                            /___/ "
echo -e ""
echo -e "               =========[ LED B860H ]========="
echo -e "             ========[GPIO Founder REYRE]========"
echo -e "          =======[SCRIPT INSTALL by MahaVPN]========"
echo -e ""
read -p "Hubungi @AfthonPC jika script error...Masukkan password yang benar : " goodboy
if [ $goodboy = $owner ]; then
clear
echo -e "Permintaan SAH"
else
clear
echo -e "Permintaan Ditolak, masukkan password yang benar!";
echo "Harap hubungi @AfthonPc"
read -p "Pres enter to try again : " wkwk
bash /root/led
fi
clear
rm -rf /usr/bin/bled
rm -rf /usr/bin/bledon
rm -rf /usr/bin/rc.local.txt
wget -P /root "https://raw.githubusercontent.com/GboyGud/mahavpn/main/led_b860h/LED_B860H_v1v2.zip"
unzip /root/LED_B860H_v1v2.zip -d /usr/bin
chmod +x /usr/bin/bled
chmod +x /usr/bin/bledon
chmod +x /usr/bin/rc.local.txt
rm /root/LED_B860H_v1v2.zip
sed -i '$ i\sleep 20 && /usr/bin/bled -r' /etc/rc.local
/usr/bin/bled -r
rm /root/led
clear
echo -e "alhamdulillah sudah kelar yagesya"
echo -e "Matur Tengkyu @AfthonPc"
